# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RSAarma <- function(pData, pDataCol, pDataNum, pSampleNum, pStepscale, pTotal_Iteration, pWarm) {
    .Call(`_SAMCpack_RSAarma`, pData, pDataCol, pDataNum, pSampleNum, pStepscale, pTotal_Iteration, pWarm)
}

exec_SAMC <- function(func, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init) {
    .Call(`_SAMCpack_exec_SAMC`, func, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init)
}

exec_SAMCoptim <- function(func, nv, energy, domain, niter, vecpi, t0, xi, stepsize, init, tau_h, tau_star, tau_t0, trunc_init, trunc_r) {
    .Call(`_SAMCpack_exec_SAMCoptim`, func, nv, energy, domain, niter, vecpi, t0, xi, stepsize, init, tau_h, tau_star, tau_t0, trunc_init, trunc_r)
}

exec_samcfast_type0 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init) {
    .Call(`_SAMCpack_exec_samcfast_type0`, func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init)
}

exec_samcfast_type1 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data) {
    .Call(`_SAMCpack_exec_samcfast_type1`, func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data)
}

exec_samcfast_type2 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data) {
    .Call(`_SAMCpack_exec_samcfast_type2`, func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data)
}

exec_samcfast_type3 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data) {
    .Call(`_SAMCpack_exec_samcfast_type3`, func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data)
}

exec_samcfast_sexpdata <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data) {
    .Call(`_SAMCpack_exec_samcfast_sexpdata`, func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data)
}

ksSAMCrsa <- function(coords, Y, X, nsubset, maxiter, a0, t0, b0, eta) {
    .Call(`_SAMCpack_ksSAMCrsa`, coords, Y, X, nsubset, maxiter, a0, t0, b0, eta)
}

rescale_vert2 <- function(A) {
    .Call(`_SAMCpack_rescale_vert2`, A)
}

rescale_hori2 <- function(A) {
    .Call(`_SAMCpack_rescale_hori2`, A)
}

sample_int <- function(n, k) {
    .Call(`_SAMCpack_sample_int`, n, k)
}

