# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exec_SAMC <- function(func, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init) {
    .Call('_SAMCpack_exec_SAMC', PACKAGE = 'SAMCpack', func, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init)
}

exec_samcfast_type0 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init) {
    .Call('_SAMCpack_exec_samcfast_type0', PACKAGE = 'SAMCpack', func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init)
}

exec_samcfast_type1 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data) {
    .Call('_SAMCpack_exec_samcfast_type1', PACKAGE = 'SAMCpack', func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data)
}

exec_samcfast_type2 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data) {
    .Call('_SAMCpack_exec_samcfast_type2', PACKAGE = 'SAMCpack', func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data)
}

exec_samcfast_type3 <- function(func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data) {
    .Call('_SAMCpack_exec_samcfast_type3', PACKAGE = 'SAMCpack', func_, nv, energy, domain, tau, niter, vecpi, t0, xi, stepsize, trange, init, data)
}

rescale_vert2 <- function(A) {
    .Call('_SAMCpack_rescale_vert2', PACKAGE = 'SAMCpack', A)
}

rescale_hori2 <- function(A) {
    .Call('_SAMCpack_rescale_hori2', PACKAGE = 'SAMCpack', A)
}

rcpparma_hello_world <- function() {
    .Call('_SAMCpack_rcpparma_hello_world', PACKAGE = 'SAMCpack')
}

rcpparma_outerproduct <- function(x) {
    .Call('_SAMCpack_rcpparma_outerproduct', PACKAGE = 'SAMCpack', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_SAMCpack_rcpparma_innerproduct', PACKAGE = 'SAMCpack', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_SAMCpack_rcpparma_bothproducts', PACKAGE = 'SAMCpack', x)
}

